#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

S3DF_USER="${S3DF_USER:-monarin}"
S3DF_DIR="${S3DF_DIR:-${HOME}/.ssh/s3df}"
SSH_CONFIG="${SSH_CONFIG:-${HOME}/.ssh/config}"
S3DF_CONF="${S3DF_CONF:-${S3DF_DIR}/s3df.conf}"
STATE_FILE="${S3DF_STATE_FILE:-${S3DF_DIR}/.last-register}"
PENDING_FILE="${S3DF_PENDING_FILE:-${S3DF_DIR}/.pending-key}"
PUBLIC_KEY_FILE="${S3DF_PUBLIC_KEY_FILE:-${S3DF_DIR}/.pending-public-key.ssh2}"
LOG_FILE="${S3DF_LOG_FILE:-${S3DF_DIR}/preconnect.log}"
SUBMITTER="${S3DF_SUBMITTER:-${REPO_ROOT}/scripts/s3df-submit-key.mjs}"
REFRESH_INTERVAL_SECONDS="${S3DF_REFRESH_INTERVAL_SECONDS:-72000}"
VERIFY_HOST="${S3DF_VERIFY_HOST:-sdflogin002}"
VERIFY_TIMEOUT_SECONDS="${S3DF_VERIFY_TIMEOUT_SECONDS:-10}"
PLAYWRIGHT_PROFILE_DIR="${S3DF_PLAYWRIGHT_PROFILE_DIR:-${HOME}/Library/Application Support/s3df-key-refresh/chrome-profile}"
S3DF_REGISTER_URL="${S3DF_REGISTER_URL:-https://s3df-sshkeys.slac.stanford.edu/register/${S3DF_USER}}"
S3DF_KEY_LIST_URL="${S3DF_KEY_LIST_URL:-https://s3df-sshkeys.slac.stanford.edu/list/${S3DF_USER}}"
S3DF_LOGIN_HOST_PATTERNS="${S3DF_LOGIN_HOST_PATTERNS:-s3dflogin s3dflogin.slac.stanford.edu sdflogin sdflogin00? sdflogin*.slac.stanford.edu}"
S3DF_INTERNAL_HOST_PATTERNS="${S3DF_INTERNAL_HOST_PATTERNS:-psbuildrc psbuild-rocky9 psbuild-rocky9-01 sdfiana sdfiana00? drp-srcf-gpu003}"
S3DF_INTERNAL_KEY="${S3DF_INTERNAL_KEY:-${S3DF_DIR}/s3df-internal-ed25519}"

FORCE=0
DRY_RUN=0
WRITE_CONFIG_ONLY=0

usage() {
    cat <<EOF
Usage: $(basename "$0") [--force] [--dry-run] [--write-config]

Refresh an S3DF SSH key registration before VS Code Remote-SSH connects.

Environment overrides:
  S3DF_USER
  S3DF_REFRESH_INTERVAL_SECONDS
  S3DF_REGISTER_URL
  S3DF_KEY_LIST_URL
  S3DF_VERIFY_HOST
  S3DF_VERIFY_TIMEOUT_SECONDS
  S3DF_PLAYWRIGHT_PROFILE_DIR
  S3DF_LOG_FILE
  S3DF_LOGIN_HOST_PATTERNS
  S3DF_INTERNAL_HOST_PATTERNS
  S3DF_INTERNAL_KEY
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)
            FORCE=1
            ;;
        --dry-run)
            DRY_RUN=1
            ;;
        --write-config)
            WRITE_CONFIG_ONLY=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

file_mtime() {
    stat -f %m "$1" 2>/dev/null || stat -c %Y "$1"
}

log_event() {
    local message="$1"

    {
        printf '%s pid=%s %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$$" "$message"
    } >> "$LOG_FILE" 2>/dev/null || true
}

latest_private_key() {
    find "$S3DF_DIR" -type f -name 'SHA256:*' ! -name '*.pub' -print 2>/dev/null | sort | tail -n 1
}

registered_private_keys() {
    local registered_key=""

    if [[ -f "$STATE_FILE" ]]; then
        registered_key="$(awk -F= '$1 == "key" {print substr($0, 5)}' "$STATE_FILE" | tail -n 1)"
    fi

    if [[ -n "$registered_key" && -f "$registered_key" ]]; then
        printf '%s\n' "$registered_key"
        return 0
    fi

    find "$S3DF_DIR" -type f -name 'SHA256:*' ! -name '*.pub' -print 2>/dev/null | sort
}

has_fresh_registration() {
    [[ -f "$STATE_FILE" ]] || return 1

    local now
    local mtime
    local age
    now="$(date +%s)"
    mtime="$(file_mtime "$STATE_FILE")"
    age=$((now - mtime))

    [[ "$age" -lt "$REFRESH_INTERVAL_SECONDS" ]]
}

verify_registered_login() {
    ssh \
        -o BatchMode=yes \
        -o NumberOfPasswordPrompts=0 \
        -o ConnectTimeout="$VERIFY_TIMEOUT_SECONDS" \
        -o ControlMaster=no \
        -o ControlPath=none \
        "$VERIFY_HOST" true >/dev/null 2>&1
}

ensure_dirs() {
    umask 077
    mkdir -p "$S3DF_DIR"
    chmod 700 "$S3DF_DIR"
    mkdir -p "${HOME}/.ssh/controlmasters"
    chmod 700 "${HOME}/.ssh" "${HOME}/.ssh/controlmasters" 2>/dev/null || true
}

ensure_ssh_include() {
    local include_line="Include ~/.ssh/s3df/s3df.conf"
    local tmp

    touch "$SSH_CONFIG"
    chmod 600 "$SSH_CONFIG"

    if grep -Fqx "$include_line" "$SSH_CONFIG"; then
        return 0
    fi

    tmp="${SSH_CONFIG}.s3df.$$"
    {
        printf '%s\n\n' "$include_line"
        cat "$SSH_CONFIG"
    } > "$tmp"
    chmod 600 "$tmp"
    mv "$tmp" "$SSH_CONFIG"
}

write_s3df_conf() {
    local tmp
    tmp="${S3DF_CONF}.tmp.$$"

    {
        printf '# Generated by %s on %s\n' "$0" "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        printf 'Host'
        # shellcheck disable=SC2086
        for host_pattern in $S3DF_LOGIN_HOST_PATTERNS; do
            printf ' %s' "$host_pattern"
        done
        printf '\n'
        registered_private_keys | while IFS= read -r key_path; do
            printf '  IdentityFile %s\n' "$key_path"
        done
        printf '  IdentitiesOnly yes\n'

        if [[ -f "$S3DF_INTERNAL_KEY" ]]; then
            printf '\nHost'
            # shellcheck disable=SC2086
            for host_pattern in $S3DF_INTERNAL_HOST_PATTERNS; do
                printf ' %s' "$host_pattern"
            done
            printf '\n'
            printf '  IdentityFile %s\n' "$S3DF_INTERNAL_KEY"
            printf '  IdentitiesOnly yes\n'
        fi
    } > "$tmp"

    chmod 600 "$tmp"
    mv "$tmp" "$S3DF_CONF"
}

generate_or_reuse_pending_key() {
    local pending_key
    local tmp_key
    local fingerprint
    local key_path

    if [[ -s "$PENDING_FILE" ]]; then
        pending_key="$(cat "$PENDING_FILE")"
        if [[ -f "$pending_key" ]]; then
            printf '%s\n' "$pending_key"
            return 0
        fi
    fi

    tmp_key="${S3DF_DIR}/temp-key.$$"
    ssh-keygen -q -t ed25519 -f "$tmp_key" -C "$S3DF_USER" -N ""
    fingerprint="$(ssh-keygen -lf "$tmp_key" | awk '{print $2}' | sed 's|[/+]|.|g')"
    key_path="${S3DF_DIR}/${fingerprint}"

    if [[ -e "$key_path" || -e "${key_path}.pub" ]]; then
        key_path="${S3DF_DIR}/${fingerprint}.$(date +%s)"
    fi

    mv "$tmp_key" "$key_path"
    mv "${tmp_key}.pub" "${key_path}.pub"
    chmod 600 "$key_path" "${key_path}.pub"
    printf '%s\n' "$key_path" > "$PENDING_FILE"
    chmod 600 "$PENDING_FILE"
    printf '%s\n' "$key_path"
}

export_public_key() {
    local key_path="$1"

    ssh-keygen -e -f "$key_path" > "$PUBLIC_KEY_FILE"
    chmod 600 "$PUBLIC_KEY_FILE"
}

key_fingerprint() {
    local key_path="$1"

    ssh-keygen -lf "$key_path" | awk '{print $2}' | sed 's|[/+]|.|g'
}

ensure_playwright_dependency() {
    if (cd "$REPO_ROOT" && node -e "import('playwright').then(() => {}).catch(() => process.exit(1))") >/dev/null 2>&1; then
        return 0
    fi

    cat >&2 <<EOF
Missing Node dependency: playwright

Install it once with:
  cd "$REPO_ROOT"
  npm install
EOF
    return 1
}

register_public_key() {
    local submit_args=(
        "$SUBMITTER"
        --mode register
        --public-key-file "$PUBLIC_KEY_FILE"
        --user "$S3DF_USER"
        --url "$S3DF_REGISTER_URL"
        --profile-dir "$PLAYWRIGHT_PROFILE_DIR"
    )

    if [[ "$DRY_RUN" -eq 1 ]]; then
        submit_args+=(--dry-run)
    fi

    (cd "$REPO_ROOT" && node "${submit_args[@]}")
}

refresh_registered_key() {
    local fingerprint="$1"
    local submit_args=(
        "$SUBMITTER"
        --mode refresh
        --fingerprint "$fingerprint"
        --user "$S3DF_USER"
        --url "$S3DF_KEY_LIST_URL"
        --profile-dir "$PLAYWRIGHT_PROFILE_DIR"
    )

    if [[ "$DRY_RUN" -eq 1 ]]; then
        submit_args+=(--dry-run)
    fi

    (cd "$REPO_ROOT" && node "${submit_args[@]}")
}

record_success() {
    local key_path="$1"
    local operation="$2"
    local url="$3"

    {
        printf 'registered_at=%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        printf 'user=%s\n' "$S3DF_USER"
        printf 'key=%s\n' "$key_path"
        printf 'operation=%s\n' "$operation"
        printf 'url=%s\n' "$url"
    } > "$STATE_FILE"
    chmod 600 "$STATE_FILE"
    rm -f "$PENDING_FILE" "$PUBLIC_KEY_FILE"
}

main() {
    ensure_dirs
    trap 'status=$?; if [[ "$status" -ne 0 ]]; then log_event "exit status=${status}"; fi' EXIT
    log_event "start user=${S3DF_USER} force=${FORCE} dry_run=${DRY_RUN} write_config=${WRITE_CONFIG_ONLY}"

    if [[ "$WRITE_CONFIG_ONLY" -eq 1 ]]; then
        ensure_ssh_include
        write_s3df_conf
        log_event "write_config complete"
        echo "S3DF SSH config written."
        exit 0
    fi

    local existing_key
    existing_key="$(registered_private_keys | head -n 1)"

    if [[ "$FORCE" -eq 0 && -n "$existing_key" ]] && has_fresh_registration; then
        ensure_ssh_include
        write_s3df_conf
        if verify_registered_login; then
            log_event "skip fresh_registration key=${existing_key} verify_host=${VERIFY_HOST}"
            echo "S3DF key registration is fresh; skipping refresh."
            exit 0
        fi
        log_event "fresh_registration_rejected key=${existing_key} verify_host=${VERIFY_HOST}"
        echo "S3DF key registration is fresh by timestamp but rejected by ${VERIFY_HOST}; refreshing."
    fi

    ensure_playwright_dependency

    if [[ -n "$existing_key" ]]; then
        local existing_fingerprint
        local refresh_status
        existing_fingerprint="$(key_fingerprint "$existing_key")"

        log_event "refresh begin key=${existing_key}"
        echo "Refreshing existing S3DF public key for ${S3DF_USER}."
        if refresh_registered_key "$existing_fingerprint"; then
            log_event "refresh ok key=${existing_key}"

            if [[ "$DRY_RUN" -eq 1 ]]; then
                log_event "dry_run refresh complete key=${existing_key}"
                echo "Dry run complete; not recording refresh success."
                exit 0
            fi

            record_success "$existing_key" refresh "$S3DF_KEY_LIST_URL"
            ensure_ssh_include
            write_s3df_conf
            log_event "recorded refresh success key=${existing_key}"
            echo "S3DF key registration refreshed for ${S3DF_USER}."
            exit 0
        else
            refresh_status=$?
        fi

        if [[ "$refresh_status" -ne 3 ]]; then
            log_event "refresh failed key=${existing_key} status=${refresh_status}"
            return "$refresh_status"
        fi

        log_event "refresh target_missing key=${existing_key}"
        echo "Existing S3DF key is not listed; registering a new public key."
    fi

    local key_path
    key_path="$(generate_or_reuse_pending_key)"
    export_public_key "$key_path"
    log_event "submit begin key=${key_path}"

    echo "Submitting S3DF public key for ${S3DF_USER}."
    register_public_key
    log_event "submit ok key=${key_path}"

    if [[ "$DRY_RUN" -eq 1 ]]; then
        log_event "dry_run complete key=${key_path}"
        echo "Dry run complete; not recording registration success."
        exit 0
    fi

    record_success "$key_path" register "$S3DF_REGISTER_URL"
    ensure_ssh_include
    write_s3df_conf
    log_event "recorded success key=${key_path}"
    echo "S3DF key registration recorded for ${S3DF_USER}."
}

main
